
alias g="git"
# post a gist file to github if the gist tool is in the path
alias gist-diff="gist --type diff"

# Git aliases
alias ga="git a"
alias gac="git ac"
alias gb="git b"
alias gba="git ba"
alias gbc="git bc"
alias gbd="git bd"
alias gci="git ci --no-verify"
alias gcia="git cia --no-verify"
alias gcim="git cim --no-verify"
alias gciv="git civ"
alias gcl="git cl"
alias gclf="git clf"
alias gco="git co"
alias gcob="git cob"
alias gcom="git com"
alias gcop="git cop"
alias gd="git d"
alias gdc="git dc"
alias gdcs="git dcs"
alias gdm="git dm"
alias gdms="git dms"
alias gds="git ds"
alias gdw="git dw"
alias gf="git f"
alias gfp="git fp"
alias gg="git g"
alias gl="git l"
alias glo="git lo"
alias glh="git lh"
alias glhs="git lhs"
alias glp="git lp"
alias glpj="git lpj"
alias gls="git ls"
alias gmv="git mv"
alias gr="git r"
alias gra="git ra"
alias grc="git rc"
alias gre="git re"
alias greh="git reh"
alias grehh="git rehh"
alias gri="git ri"
alias grih2="git rih2"
alias grih3="git rih3"
alias grih4="git rih4"
alias grih5="git rih5"
alias grih= "git rih"
alias grmc="git rmc"
alias grpull="git rpull"
alias grs="git rs"
alias gs="git s"
alias gsa="git sa"
alias gsh="git sh"
alias gshs="git shs"
alias gsnp="git snp"
alias gst="git st"
alias gstm="git stm"

# GitHub CLI aliases
alias ghc="gh pr checkout"

alias co="codex -m gpt-5-codex --search"

# Project directories
alias circuit="cd ~/src/autonomy/circuit"

# Claude
alias claude-dangerous="claude --dangerously-skip-permissions"
