alias g="git"
alias s="git grep -e \"$1\""
alias be="bundle exec"
alias lss="ls -1"


export WORK="~/work"
export OS="~/src/_os"
export MAR="$OS/marionette"

alias work="cd $WORK"
alias os="cd $OS"
alias m="cd $MAR"

alias rc="vim ~/.zshrc"
alias src="source ~/.zshrc"

alias rmswp="rm **/.*swp"

alias gist-diff="gist --type diff"

alias v="vim"
alias vd="git dms | fpp -c vim"
alias vl="git lhs | fpp -c vim"
alias vsh="git show HEAD --numstat | fpp -c vim"



alias ga="git a"
alias gac="git ac"
alias gb="git b"
alias gba="git ba"
alias gbc="git bc"
alias gbd="git bd"
alias gci="git ci"
alias gcia="git cia"
alias gcim="git cim"
alias gciv="git civ"
alias gcl="git cl"
alias gclf="git clf"
alias gco="git co"
alias gcom="git com"
alias gcob="git cob"
alias gcop="git cop"
alias gd="git d"
alias gds="git ds"
alias gdc="git dc"
alias gdcs="git dcs"
alias gdm="git dm"
alias gdms="git dms"
alias gdw="git dw"
alias gf="git f"
alias gfp="git fp"
alias gg="git g"
alias gl="git l"
alias glp="git lp"
alias glpj="git lpj"
alias gls="git ls"
alias glh="git lh"
alias glhs="git lhs"
alias grpull="git rpull"
alias gr="git r"
alias grc="git rc"
alias grs="git rs"
alias gra="git ra"
alias gri="git ri"
alias grih="git rih"
alias gre="git re"
alias greh="git reh"
alias grehh="git rehh"
alias grmc="git rmc"
alias gsh="git sh"
alias gshs="git shs"
alias gst="git st"
alias gstm="git stm"
alias gs="git s"
alias gsa="git sa"
alias gsnp="git snp"
alias gmv="git mv"
